import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "./header";
import { Footer } from "./footer";
import { SupabaseProvider } from "./context/SupabaseContext";
import QueryProvider from "@/lib/QueryClientComponentWrapper";
import SessionProvider from "@/lib/supabase/SessionProvider";
import { Providers } from "./atom/providers";
import { createStore, Provider } from "jotai";
import { DevTools } from "jotai-devtools";
import { NotificationProvider } from "./context/NotificationContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Renown",
  description: "Generated by create next app",
};

const customStore = createStore();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen text-base md:text-xl font-serif tracking-wide overflow-x-hidden bg-gradient-to-r from-orange-100 via-white to-pink-100",
          fontSans.variable
        )}
      >
        <Providers>
          <div className="flex flex-col min-h-screen w-full">
            <Header />
            <main className="flex-1 relative w-full">
              <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-full">
                {children}
              </div>
              <Footer />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
